=== llewelld/MATTS/Scenarios/VProgs/DataFlowPaper/compose.dtd
<!ENTITY % actparams	"id		ID		#IMPLIED
				init		CDATA		#IMPLIED
				cond		CDATA		#IMPLIED
				action	CDATA		#IMPLIED">
<!ENTITY % ioparams	"%actparams;
				config	IDREF	#IMPLIED">
<!ENTITY % fullparams	"%ioparams;
				format	CDATA	#IMPLIED
				cycle		(required | disallow | optional)	'optional'
				follow	(yes | no | fresh)			'fresh'">

<!ELEMENT compose		ANY>
<!ELEMENT sandbox		(#PCDATA)>
<!ELEMENT property	(#PCDATA)>
<!ELEMENT configuration	(component)*>
<!ELEMENT component	(input | output | component | process)*>
<!ELEMENT input		EMPTY>
<!ELEMENT output		EMPTY>
<!ELEMENT process		(process)*>

<!ATTLIST compose		xmlns		CDATA		#FIXED			"http://www.cms.livjm.ac.uk/PUCsec/compose"
				type		(standard | extended)			"standard">
<!ATTLIST sandbox		id		ID		#REQUIRED
				config	IDREFS	#REQUIRED>
<!ATTLIST property	id		ID		#REQUIRED>
<!ATTLIST configuration	id		ID		#REQUIRED>
<!ATTLIST component	%actparams;>
<!ATTLIST input		%fullparams;>
<!ATTLIST output		%fullparams;>
<!ATTLIST process		%ioparams;>

=== llewelld/MATTS/Scenarios/VProgs/Boundary/Boundary03.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s3" config="c1">Boundary check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="idExt">External component</property>
  <property id="idEnc">Encrypted link</property>

  <configuration id="c1" init="1">
    <component>
      <process action="@ncol[@n][0]"/>
      <process id="safe" init="1" action="safe=1"/>
      <process init="0" cond="@a[@n][idExt]" action="safe=2" config="check"/>
      <input format="" cond="safe&gt;=1"/>
      <input format="*" cond="safe&gt;=1"/>
      <output format="*" config="c1" cond="safe==1"/>
      <output format="*" follow = "no" cond="safe==2"/>
      <output format=""/>
    </component>
  </configuration>

  <process id="check">
    <process action="@ncol[@n][#ff0000]"/>
    <process action="link=@ilnum[@n]"/>
    <process id="link" init="0">
      <process action="link=(link-1)"/>
      <process action="@ncol[@iln[@n][link]][#00ff00]"/>
      <process init="0" cond="(!@a[@iln[@n][link]][idExt]) &amp;&amp; (!@ao[@iln[@n][link]][@ilol[@n][link]][idEnc])" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process cond="link &gt; 0" config="link"/>
    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/Access/Access2.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Access control check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <output id="out1" init="0" format="*"/>
      <component>
        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" config="c2"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <process id="check" init="0">
    <process id="stack_pos" init="0" action="@v=0"/>
    <process id="node_stack" init="0" action="@v=check"/>
    <process id="link_stack" init="0" action="@v=0"/>
    <process id="node_visited" init="0" action="@v=0"/>
    <process id="recurse">
      <process id="current_node" action="@v=node_stack[stack_pos]"/>
      <process id="current_link" action="@v=link_stack[stack_pos]"/>
      <process action="node_visited[current_node]=1"/>
      <process id="find_link">
        <process id="next_node" action="@v=@iln[current_node][current_link]"/>
        <process action="current_link=(current_link+1)"/>
        <process config="find_link" cond="(current_link &gt;= @ilnum[current_node]) || (node_visited[next_node]=0)"/>
      </process>
      <process cond="current_link &lt; @ilnum[current_node]" action="(link_stack[stack_pos]=current_link) && (stack_pos=(stack_pos+1)) && (node_stack[stack_pos]=next_node) && (link_stack[stack_pos]=0" config="recurse"/>
      <process cond="(current_link &gt;= @ilnum[current_node]) && (stack_pos &gt;= 0)" action="stack_pos=(stack_pos-1) config="recurse"/>
    </process>
  </process>




</compose>

=== llewelld/MATTS/Scenarios/VProgs/DataFlowPaper/AccessSensitivity.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="ReadAccess" config="c1">Read access control check using Sensitivity Levels</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="DataSensitivity">Level of access read by component</property>
  <property id="Write">Level of access written by component (not used)</property>
  <property id="SensitivityLevel">Level of access component is authorised to</property>

  <configuration id="c1">
    <component>
      <process id="compliant" init="1"/>
      <process action="@ncol[@n][0]"/>
      <process id="authority" init="1" action="@a[@n][0][SensitivityLevel]"/>
      <process config="check" action="check=@n"/>
      <process cond="result &lt; authority" action="compliant = 0"/>

      <input format=""/>
      <input format="*"/>

      <process action="@ncol[@n][#005555]" cond="compliant != 1"/>
      <output format="*" config="c1" follow="fresh" cond="compliant == 1"/>
      <output format="" cond="compliant==1"/>
    </component>
  </configuration>

  <process id="check" init="0">
    <process id="result" init="0" action="@v=(0-1)"/>
    <process id="stack_pos" init="0" action="@v=0"/>
    <process id="node_stack" init="0" action="@v=check"/>
    <process id="link_stack" init="0" action="@v=0"/>
    <process id="node_visited" init="0" action="@v=0"/>
    <process id="recurse">
      <process id="current_node" init="0" action="@v=node_stack[stack_pos]"/>

      <process id="read" init="0" action="@a[current_node][0][DataSensitivity]"/>
      <process action="@ncol[current_node][#0055ff]" cond="read &lt; authority"/>
      <process cond="(result &lt; 0) || (result &gt; read)" action="result=read"/>

      <process id="current_link" init="0" action="@v=link_stack[stack_pos]"/>
      <process action="node_visited[(current_node + 1)]=1"/>
      <process id="find_link">
        <process id="next_node" init="0" action="@v=@iln[current_node][current_link]" cond="current_link &lt; @ilnum[current_node]"/>
        <process config="find_link" cond="(current_link &lt; @ilnum[current_node]) &amp;&amp; (node_visited[(next_node + 1)]==1)" action="current_link=(current_link+1)"/>
        <process cond="(current_link &lt; @ilnum[current_node]) &amp;&amp; (node_visited[(next_node + 1)]==0)" action="(link_stack[stack_pos]=(current_link+1)) &amp;&amp; (stack_pos=(stack_pos+1)) &amp;&amp; (node_stack[stack_pos]=next_node) &amp;&amp; (link_stack[stack_pos]=0)" config="recurse"/>
        <process cond="(current_link &gt;= @ilnum[current_node]) &amp;&amp; (stack_pos &gt;= 0)" action="stack_pos=(stack_pos-1)" config="recurse"/>
      </process>
    </process>
  </process>


</compose>

=== llewelld/MATTS/Scenarios/VProgs/Test.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s1" config="c1">Test any</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0 1 2 3 4" format="*"/>
      <output id="out1" init="0" format="*" config="c1" action="in1[3]=5" cond="in1[0]==0"/>
      <output format=""/>
    </component>
  </configuration>

</compose>
