=== llewelld/MATTS/Scenarios/VProgs/DataFlowPaper/compose.dtd
<!ENTITY % actparams	"id		ID		#IMPLIED
				init		CDATA		#IMPLIED
				cond		CDATA		#IMPLIED
				action	CDATA		#IMPLIED">
<!ENTITY % ioparams	"%actparams;
				config	IDREF	#IMPLIED">
<!ENTITY % fullparams	"%ioparams;
				format	CDATA	#IMPLIED
				cycle		(required | disallow | optional)	'optional'
				follow	(yes | no | fresh)			'fresh'">

<!ELEMENT compose		ANY>
<!ELEMENT sandbox		(#PCDATA)>
<!ELEMENT property	(#PCDATA)>
<!ELEMENT configuration	(component)*>
<!ELEMENT component	(input | output | component | process)*>
<!ELEMENT input		EMPTY>
<!ELEMENT output		EMPTY>
<!ELEMENT process		(process)*>

<!ATTLIST compose		xmlns		CDATA		#FIXED			"http://www.cms.livjm.ac.uk/PUCsec/compose"
				type		(standard | extended)			"standard">
<!ATTLIST sandbox		id		ID		#REQUIRED
				config	IDREFS	#REQUIRED>
<!ATTLIST property	id		ID		#REQUIRED>
<!ATTLIST configuration	id		ID		#REQUIRED>
<!ATTLIST component	%actparams;>
<!ATTLIST input		%fullparams;>
<!ATTLIST output		%fullparams;>
<!ATTLIST process		%ioparams;>

=== llewelld/MATTS/Scenarios/VProgs/binary.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="standard">

  <sandbox id="s2" config="c3">Binary tree</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c3">
    <component id="c4">
      <input format=""/>
      <output format="id1 id1" cycle="disallow"/>
      <component id="c5">
        <input format="id1" cycle="disallow"/>
        <output config="c4" format="id1 id1" cycle="disallow"/>
        <output format=""/>
      </component>
    </component>
  </configuration>


</compose>

=== llewelld/MATTS/Scenarios/VProgs/DataFlowPaper/AssessLink.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="ReadAccess" config="c1">Read access control check using Sensitivity Levels</sandbox>
  <property id="Any">Defined to be any property</property>
  <property id="Write">Level of access written by component (not used)</property>
  

  <configuration id="c1">
    <component>
      <process id="compliant" init="1" action="@v=1"/>
      <process id="channelNum" init="0" action="@v=0"/>
           
      <process id="authority" init="10" action="@a[@n][0][SensitivityLevel]"/>
      <process config="check" cond="(@olnum[@n] &gt; 0)"/>
      
      <input format=""/>
      <input format="*"/>

      <process action="@ncol[@n][#005555]" cond="compliant != 1"/>
      <output format="*" config="c1" follow="fresh" cond="compliant == 1"/>
      <output format="" cond="compliant==1"/>
    </component>
  </configuration>
  <process id="check">
     <process id="channelId" init="0" action="channelId[channelNum] = @ao[@n][channelNum][ChannelOut]"/>
     <process id="dataSL" init="10" action="dataSL[channelNum] = @ao[@n][channelNum][SensitivityLevel]"/>
     
     <process id="next_node_SL" init="10" action="@a[@oln[@n][channelNum]][0][SensitivityLevel]"/>
     <process cond="(next_node_SL &gt; dataSL[channelNum]) || (authority &gt; dataSL[channelNum])" action="compliant = 0"/>
     <process action="@ncol[@oln[@n][channelNum]][#0055ff]" cond="next_node_SL &gt; dataSL[channelNum]"/>
     <process action="channelNum=(channelNum+1)"/>
     <process config="check"  cond="channelNum &lt; @olnum[@n]"/>
  </process>



</compose>

=== llewelld/MATTS/Scenarios/VProgs/WildCard.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c3">Tree</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c3">
    <component id="c4">
      <input format=""/>
      <output format="*" cycle="disallow"/>
      <component>
        <input format="id1*" cycle="disallow"/>
        <output config="c4" format="*" cycle="disallow"/>
        <output format=""/>
      </component>
      <component>
        <input format = "id2*"/>
        <output format="external"/>
      </component>
    </component>
  </configuration>


</compose>

=== llewelld/MATTS/Scenarios/VProgs/Access2.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Read access control check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="idRead">Level of access read by component</property>
  <property id="idWrite">Level of access written by component</property>
  <property id="idAuthority">Level of access component is authorised to</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <output id="out1" init="0" format="*"/>
      <component>
        <process config="check" action="check=@n"/>
        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" config="c2" follow="fresh"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <process id="check" init="0">
    <process id="stack_pos" init="0" action="@v=0"/>
    <process id="node_stack" init="0" action="@v=check"/>
    <process id="link_stack" init="0" action="@v=0"/>
    <process id="node_visited" init="0" action="@v=0"/>
    <process id="recurse">
      <process id="current_node" init="0" action="@v=node_stack[stack_pos]"/>
      <process id="current_link" init="0" action="@v=link_stack[stack_pos]"/>
      <process action="node_visited[current_node]=1"/>
      <process id="find_link">
        <process id="next_node" init="0" action="@v=@iln[current_node][current_link]" cond="current_link &lt; @ilnum[current_node]"/>
        <process config="find_link" cond="(current_link &lt; @ilnum[current_node]) &amp;&amp; (node_visited[next_node]==1)" action="current_link=(current_link+1)"/>
        <process cond="(current_link &lt; @ilnum[current_node]) &amp;&amp; (node_visited[next_node]==0)" action="(link_stack[stack_pos]=(current_link+1)) &amp;&amp; (stack_pos=(stack_pos+1)) &amp;&amp; (node_stack[stack_pos]=next_node) &amp;&amp; (link_stack[stack_pos]=0)" config="recurse"/>
        <process cond="(current_link &gt;= @ilnum[current_node]) &amp;&amp; (stack_pos &gt;= 0)" action="stack_pos=(stack_pos-1)" config="recurse"/>
      </process>
    </process>
  </process>




</compose>

=== llewelld/MATTS/Scenarios/VProgs/Boundary/Boundary04.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s3" config="c1">Boundary check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="External">External component</property>
  <property id="idEnc">Encrypted link</property>

  <configuration id="c1" init="1">
    <component>
      <process action="@ncol[@n][0]"/>
      <process id="safe" init="1" action="safe=1"/>
      <process init="0" cond="@a[@n][External]" action="safe=2" config="check"/>
      <input format="" cond="safe&gt;=1"/>
      <input format="*" cond="safe&gt;=1"/>
      <output format="*" config="c1" cond="safe==1"/>
      <output format="*" follow = "no" cond="safe==2"/>
      <output format=""/>
    </component>
  </configuration>

  <process id="check">
    <process action="@ncol[@n][#ff0000]"/>
    <process action="link=@ilnum[@n]"/>
    <process id="link" init="0">
      <process action="link=(link-1)"/>
      <process action="@ncol[@iln[@n][link]][#00ff00]"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (!@a[@iln[@n][link]][Firewall]) &amp;&amp; (!@a[@iln[@n][link]][IDS])" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 0) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 11) || (@a[@iln[@n][link]][StaffSkills] &lt; 3))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 1) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 11) || (@a[@iln[@n][link]][StaffSkills] &lt; 3))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 2) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 11) || (@a[@iln[@n][link]][StaffSkills] &lt; 2))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 3) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 8) || (@a[@iln[@n][link]][StaffSkills] &lt; 2))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 4) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 8) || (@a[@iln[@n][link]][StaffSkills] &lt; 2))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 5) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 6) || (@a[@iln[@n][link]][StaffSkills] &lt; 2))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 6) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 6) || (@a[@iln[@n][link]][StaffSkills] &lt; 2))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 7) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 6) || (@a[@iln[@n][link]][StaffSkills] &lt; 1))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 8) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 5) || (@a[@iln[@n][link]][StaffSkills] &lt; 1))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      <process init="0" cond="(!@a[@iln[@n][link]][External]) &amp;&amp; (@a[@iln[@n][link]][SensitivityLevel] == 9) &amp;&amp; ((@a[@iln[@n][link]][EncryptionStrength] &lt; 5) || (@a[@iln[@n][link]][StaffSkills] &lt; 1))" action="(safe=0) || (@ncol[@iln[@n][link]][#0055ff])"/>
      
      <process cond="link &gt; 0" config="link"/>
    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/CA.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s1" config="c3">Binary tree</sandbox>
  <sandbox id="s2" config="c6">Composable Assurance</sandbox>
  <sandbox id="s3" config="c11">Non-Interferance</sandbox>

  <property id="CA">Composable Assurance</property>
  <property id="id1">Stronger security property</property>
  <property id="Any">Any property</property>
  <property id="NI">Non-Interferance</property>

  <configuration id="c3">
    <component id="c4">
      <input format=""/>
      <output format="id1 id1" cycle="disallow"/>
      <component id="c5">
        <input format="id1" cycle="disallow"/>
        <output config="c4" format="id1 id1" cycle="disallow"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <configuration id="c8">
    <component id="c9">
      <input format=""/>
      <output format="*" cycle="disallow"/>
      <component>
        <input format="*" cycle="disallow"/>
        <output config="c9" format="*" cycle="disallow"/>
        <output format=""/>
        <output format="CA*" cycle="disallow"/>
        <component>
          <input format="CA*" cycle="disallow"/>
          <output format="external"/>
        </component>
      </component>
    </component>
  </configuration>

  <configuration id="c10">
    <component>
      <input format="*" cycle="disallow"/>
      <output config="c10" format="*" cycle="disallow"/>
      <output format=""/>
      <output format="*" cycle="disallow"/>
    </component>
    <component>
      <input format="CA*" cycle="disallow"/>
      <output format="external"/>
    </component>
  </configuration>

  <configuration id="c6">
    <component id="c7">
      <input format="" cycle="disallow"/>
      <output format="CA*" cycle="disallow"/>
      <component>
        <input format="CA*" cycle="disallow"/>
        <output config="c7" format="CA*" cycle="disallow"/>
        <output format=""/>
        <output config="c7" format="*" cycle="disallow"/>
      </component>
      <component>
        <input format="id1*" cycle="disallow"/>
        <output format="external"/>
      </component>
    </component>
  </configuration>


  <configuration id="c11">
    <component id="c12">
      <input format=""/>
      <output format="NI*"/>
      <component>
        <input format="NI*"/>
        <output config="c12" format="NI*"/>
        <output format=""/>
        <output format="external"/>
      </component>
    </component>
  </configuration>



</compose>

=== llewelld/MATTS/Scenarios/VProgs/cascade/cascade.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s3" config="cascade">Cascade vulnerability check</sandbox>
  <property id="lo">Accredited minimum security level</property>
  <property id="hi">Accredited maximum security level</property>

  <configuration id="cascade">
    <component id="path">
      <input format=""/>
      <input format="*"/>
      <process id="N" init="0" action="@v=@r" />
      <process id="problem" init="0" config="check" />
      <output format="*" cond="problem==0" config="cascade" />
      <output format="" cond="problem==0" />
    </component>
  </configuration>

  <process id="check">
    <process id="max" init="0" action="max[N]=max[(N-1)]"/>
    <process id="min" init="0" action="min[N]=min[(N-1)]"/>
    <process id="devmin" init="0" action="@a[@n][lo]"/>
    <process id="devmax" init="0" action="@a[@n][hi]"/>
    <process id="difficulty" init="0" cond="(devmax-devmin) &gt; @v" action="@v=(devmax-devmin)"/>
    <process init="0" cond="(devmax &gt; max[N])||(max[N]==0)" action="max[N]=devmax" />
    <process init="0" cond="(devmin &lt; min[N])||(min[N]==0)" action="min[N]=devmin" />
    <process init="0" cond="difficulty &lt; (max[N]-min[N])" action="problem=1" />
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/Boundary/Boundary02.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s3" config="c1">Boundary check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="idExt">External component</property>
  <property id="idEnc">Encrypted link</property>

  <configuration id="c1" init="1">
    <component id="c2">
      <process action="@ncol[@n][0]"/>
      <input format=""/>
      <input format="*"/>
      <output format="*"/>
      <component>
        <process action="@ncol[@n][0]"/>
        <process id="safelink" init="1" action="safelink=1"/>
        <process id="analyse01" init="0" cond="@a[@n][idExt]" config="check"/>
        <input format="*" cond="safelink==1"/>
        <output format="*" config="c1"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <process id="check" init="0">
    <process action="@ncol[@n][#ffff00]"/>
    <process id="link" init="0" action="link=@ilnum[@n]"/>
    <process id="link_loop">
      <process action="link=(link-1)"/>
      <process action="@ncol[@iln[@n][link]][#0000ff]"/>
      <process id="analyse02" init="0" cond="(!@a[@iln[@n][link]][idExt]) &amp;&amp; (!@ao[@iln[@n][link]][@ilol[@n][link]][idEnc])" action="safelink=0"/>
      <process cond="link &gt; 0" config="link_loop"/>
    </process>
  </process>

</compose>
