=== llewelld/MATTS/Scenarios/VProgs/DataFlowPaper/compose.dtd
<!ENTITY % actparams	"id		ID		#IMPLIED
				init		CDATA		#IMPLIED
				cond		CDATA		#IMPLIED
				action	CDATA		#IMPLIED">
<!ENTITY % ioparams	"%actparams;
				config	IDREF	#IMPLIED">
<!ENTITY % fullparams	"%ioparams;
				format	CDATA	#IMPLIED
				cycle		(required | disallow | optional)	'optional'
				follow	(yes | no | fresh)			'fresh'">

<!ELEMENT compose		ANY>
<!ELEMENT sandbox		(#PCDATA)>
<!ELEMENT property	(#PCDATA)>
<!ELEMENT configuration	(component)*>
<!ELEMENT component	(input | output | component | process)*>
<!ELEMENT input		EMPTY>
<!ELEMENT output		EMPTY>
<!ELEMENT process		(process)*>

<!ATTLIST compose		xmlns		CDATA		#FIXED			"http://www.cms.livjm.ac.uk/PUCsec/compose"
				type		(standard | extended)			"standard">
<!ATTLIST sandbox		id		ID		#REQUIRED
				config	IDREFS	#REQUIRED>
<!ATTLIST property	id		ID		#REQUIRED>
<!ATTLIST configuration	id		ID		#REQUIRED>
<!ATTLIST component	%actparams;>
<!ATTLIST input		%fullparams;>
<!ATTLIST output		%fullparams;>
<!ATTLIST process		%ioparams;>

=== llewelld/MATTS/Scenarios/VProgs/Copy of compose.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose>

  <sandbox id="s1" config="c1">A sandbox method</sandbox>
  <sandbox id="s2" config="c3">A sandbox method</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>
  <property id="id2">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format="id5" cycle="required"/>
      <input format=""/>
      <output format="id1 id1"/>
      <output format="id1 id2"/>
      <component>
        <input format="id1" cycle="disallow"/>
	<output format =""/>
	<output format ="id2" config="c3"/>
      </component>
      <component>
        <input format="id4"/>
        <output format ="id5" cycle="disallow"/>
        <component>
          <input format="id5"/>
          <output format ="id5" config="c1" cycle="required"/>
        </component>
      </component>
    </component>
    <component id="c3">
      <component>
        <input format="id2"/>
        <input format="id2 id2"/>
        <output format ="id3" config="c3"/>
        <output format =""/>
      </component>
    </component>
  <configuration>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/NewAccess01.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Access control check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <output id="out1" init="0" format="*"/>
      <component>
        <process config="check"/>
        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" cond="result==0" config="c2"/>
        <output format="" cond="result==0"/>
      </component>
    </component>
  </configuration>

  <process id="check">
    <process id="atcomp" init="0" action="atcomp=@n"/>
    <process action="link[atcomp]=0"/>
    <process id="return" init="0"/>
    <process id="prevlink" init="0"/>
    <process id="link" init="0">

      <process id="result" init="0" cond="link[atcomp] &lt; @ilnum[atcomp]">
        <process action="prevlink=link[atcomp]"/>
        <process action="link[atcomp]=(prevlink+1)"/>

        <process init="0" cond="@ai[atcomp][prevlink][id3]==1" action="result=1"/>

        <process action="return[@iln[atcomp][prevlink]]=atcomp"/>
        <process action="atcomp=@iln[atcomp][prevlink]"/>

        <process config="link"/>
      </process>

      <process cond="link[atcomp] &gt;= @ilnum[atcomp]" action="atcomp=@oln[atcomp][link[atcomp]]">
        <process id="tempcomp" init="0" action="atcomp=return[atcomp]"/>
        <process cond="tempcomp!=return[atcomp]" config="link"/>
      </process>

    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/AccessLPB.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Access control check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <output id="out1" init="0" format="*"/>
      <component>
        <process config="check"/>
        <input id="in2" init="0" format="*" cond="@v==1"/>
        <output id="out2" init="0" format="*" config="c2"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <process id="check">
    <process action="link=0"/>
    <process action="in2=1"/>
    <process id="link" init="0">
      <process id="result_in" init="0" cond="link &lt; @ilnum[@n]" action="@ai[@n][link][id3]">
        <process id="result_out" init="0" action="@ao[@iln[@n][link]][@ilol[@n][link]][id3]"/>
        <process action="in2=0" cond="result_in[link] &gt; result_out[@ilol[@n][link]]"/>
        <process action="link=(link+1)"/>
        <process config="link"/>
      </process>
    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/Access/Access.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Access control check</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <output id="out1" init="0" format="*"/>
      <component>
        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" config="c2"/>
        <output format=""/>
      </component>
    </component>
  </configuration>

  <process id="check">
    <process action="link=0"/>
    <process id="link" init="0">
      <process id="result" init="0" cond="link &lt; @ilnum[@n]" action="@a[@iln[@n][link]][@ilol[@n][link]][id2]">
        <process action="in2[link]=result[@ilol[@n][link]]"/>
        <process action="link=(link+1)"/>
        <process config="link"/>
      </process>
    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/AccessReadSliced02.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Read access control check with slicing</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="idRead">Level of access read by component</property>
  <property id="idWrite">Level of access written by component</property>
  <property id="idAuthority">Level of access component is authorised to</property>

  <configuration id="c1" init="1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <process config="check" action="check=@n"/>

      <output id="out1" init="0" format="*" cond="c1==1"/>
      <component>
        <process config="check" action="check=@n"/>

        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" config="c2" follow="fresh" cond="c1==1"/>
        <output format="" cond="c1==1"/>
      </component>
    </component>
  </configuration>

  <process id="check" init="0">
    <process id="result" init="0" action="@v=(0-1)"/>
    <process id="stack_pos" init="0" action="@v=0"/>
    <process id="node_stack" init="0" action="@v=check"/>
    <process id="link_in" init="0" action="@v=(0-1)"/>
    <process id="link_out" init="0" action="@v=0"/>

    <process id="direction" init="0" action="@v=0"/>

    <process id="recurse">
      <process id="current_node" init="0" action="@v=node_stack[stack_pos]"/>
      <process id="current_link_in" init="0" action="@v=link_in[stack_pos]"/>
      <process id="current_link_out" init="0" action="@v=link_out[(2 + current_link_in + (8 * current_node))]"/>

      <process config="recurse" cond="(current_link_out &lt; @olnum[current_node])" action="(stack_pos = (stack_pos + 1)) + (node_stack[stack_pos] = @oln[current_node][current_link_out]) + (link_in[stack_pos] = @olil[current_node][current_link_out]) + (link_out[(2 + current_link_in + (8 * current_node))] = (current_link_out + 1)) + (direction = 1)"/>

<!--
      <process cond="(current_link_out &gt;= @olnum[current_node]) &amp;&amp; (direction &lt; 0)" action="(link_out[(2 + current_link_in + (8 * current_node))] = 0)"/>
-->

      <process config="recurse" cond="(current_link_out &gt;= @olnum[current_node]) &amp;&amp; (stack_pos &gt; 0)" action="(stack_pos = (stack_pos - 1)) + (direction = (0-1))"/>

    </process>
  </process>




</compose>

=== llewelld/MATTS/Scenarios/VProgs/extended.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s1" config="c1">Linear prime</sandbox>

  <property id="Any">Defined to be any property</property>
  <property id="id1">A particular property</property>

  <configuration id="c1">
    <component id="c2">
      <input format=""/>
      <input format="id1"/>
      <output format="id1"/>
      <component>
        <process id="p1" init="1" action="@=(@+1)"/>
        <process config="prime" action="p_in=p1"/>
        <input format="id1"/>
        <output format="id1" config="c2"/>
        <output format="" cond="p_out==1"/>
      </component>
    </component>
  </configuration>

  <process id="prime">
    <process id="p_in" init="0" action="(p_n=1)&amp;&amp;(p_out=0)">
      <process id="p_out" init="1" cond="(p_in%2)!=0" action="@=1">
        <process id="p_n" init="1" cond="@&lt;p_in" action="@=(@+1)">
          <process cond="(p_n&lt;p_in)&amp;&amp;((p_in%p_n)==0)" action="p_out=0"/>
          <process config="p_out"/>
        </process>
      </process>
    </process>
  </process>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/CheckProperty.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="Generic" config="c1">Check all nodes satisfy some property</sandbox>
  <property id="Any">Defined to be any property</property>

  <configuration id="c1">
    <component>
      <process id="result" init="0" action="@a[@n][IDS]"/>
      <process id="ok" init="0" action="ok = (result == 1)"/>

      <input format=""/>
      <input format="*"/>
      <output format="" cond="ok == 1"/>
      <output format="*" config="c1" cond="ok == 1"/>
    </component>
  </configuration>

</compose>

=== llewelld/MATTS/Scenarios/VProgs/AccessWrite.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE compose PUBLIC "http://www.cms.livjm.ac.uk/PUCsec/dtds/compose.dtd" "compose.dtd">
<compose type="extended">

  <sandbox id="s2" config="c1">Write access control check</sandbox>

  <property id="idWrite">Level of access written by component</property>
  <property id="idWAuth">Level of access component is authorised to</property>

  <configuration id="c1" init="1">
    <component id="c2">
      <input format=""/>
      <input id="in1" init="0" format="*"/>
      <process config="check" action="check=@n"/>
      <process id="authority1" init="1" action="@a[@n][0][idWAuth]"/>
      <process cond="result &lt; authority1" action="c1=0"/>

      <output id="out1" init="0" format="*" cond="c1==1"/>
      <component>
        <process config="check" action="check=@n"/>
        <process id="authority2" init="1" action="@a[@n][0][idWAuth]"/>
        <process cond="result &lt; authority2" action="c1=0"/>

        <input id="in2" init="0" format="*"/>
        <output id="out2" init="0" format="*" config="c2" follow="fresh" cond="c1==1"/>
        <output format="" cond="c1==1"/>
      </component>
    </component>
  </configuration>

  <process id="check" init="0">
    <process id="result" init="0" action="@v=(0-1)"/>
    <process id="stack_pos" init="0" action="@v=0"/>
    <process id="node_stack" init="0" action="@v=check"/>
    <process id="link_stack" init="0" action="@v=0"/>
    <process id="node_visited" init="0" action="@v=0"/>
    <process id="recurse">
      <process id="current_node" init="0" action="@v=node_stack[stack_pos]"/>

      <process id="write" init="0" action="@a[current_node][0][idWrite]"/>
      <process cond="(result &lt; 0) || (result &gt; write)" action="result=write"/>

      <process id="current_link" init="0" action="@v=link_stack[stack_pos]"/>
      <process action="node_visited[(current_node + 1)]=1"/>
      <process id="find_link">
        <process id="next_node" init="0" action="@v=@oln[current_node][current_link]" cond="current_link &lt; @olnum[current_node]"/>
        <process config="find_link" cond="(current_link &lt; @olnum[current_node]) &amp;&amp; (node_visited[(next_node + 1)]==1)" action="current_link=(current_link+1)"/>
        <process cond="(current_link &lt; @olnum[current_node]) &amp;&amp; (node_visited[(next_node + 1)]==0)" action="(link_stack[stack_pos]=(current_link+1)) &amp;&amp; (stack_pos=(stack_pos+1)) &amp;&amp; (node_stack[stack_pos]=next_node) &amp;&amp; (link_stack[stack_pos]=0)" config="recurse"/>
        <process cond="(current_link &gt;= @olnum[current_node]) &amp;&amp; (stack_pos &gt;= 0)" action="stack_pos=(stack_pos-1)" config="recurse"/>
      </process>
    </process>
  </process>




</compose>
